version: "3.9"

services:
  omnidict-node1:
    build: .
    container_name: omnidict-node1
    ports:
      - "5001:5001" # gRPC endpoint for node1
    volumes:
      - ./data/node1:/data
    environment:
      - NODE_ID=node1
      - NODE_PORT=5001
      - RAFT_PORT=6001
      - JOIN_ADDR= # leave empty for bootstrap node
    command: ["./omnidict", "server"]

  omnidict-node2:
    build: .
    container_name: omnidict-node2
    ports:
      - "5002:5002"
    volumes:
      - ./data/node2:/data
    environment:
      - NODE_ID=node2
      - NODE_PORT=5002
      - RAFT_PORT=6002
      - JOIN_ADDR=omnidict-node1:5001
    depends_on:
      - omnidict-node1
    command: ["./omnidict", "server"]

  omnidict-node3:
    build: .
    container_name: omnidict-node3
    ports:
      - "5003:5003"
    volumes:
      - ./data/node3:/data
    environment:
      - NODE_ID=node3
      - NODE_PORT=5003
      - RAFT_PORT=6003
      - JOIN_ADDR=omnidict-node1:5001
    depends_on:
      - omnidict-node1
    command: ["./omnidict", "server"]
